[package]
name = "sunday_2021_01_03"
version = "0.1.0"
authors = ["Hanzala Ejaz <ejazhanzala2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
